#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

if grep -q ^DROPBEAR_IFDOWN= /conf/initramfs.conf; then
    # XXX backward compatibility; remove once Stretch is the current stable
    . /conf/initramfs.conf
    IFDOWN="$DROPBEAR_IFDOWN"
fi
if [ -e /etc/dropbear/config ]; then
    . /etc/dropbear/config
fi

[ "$IFDOWN" != none ] || exit 0
for IFACE in /sys/class/net/${IFDOWN:-*}; do
    [ -e "$IFACE" ] || continue
    IFACE="${IFACE#/sys/class/net/}"
    ip link    set   dev "$IFACE" down
    ip address flush dev "$IFACE"
    ip route   flush dev "$IFACE"
done
