#!/bin/sh

set -e


php_enable() { return 0; }

# Automatically added by dh_apache2
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	if php_enable; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in php7.0  ; do
				apache2_invoke dismod $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


exit 0
