#!/bin/sh

if [ -e /etc/init.d/switch_cpu_governor ]; then
  update-rc.d switch_cpu_governor remove >/dev/null
fi

if dpkg --compare-versions "${2}" lt-nl "20170619"; then
  update-rc.d -f raspi-config remove
fi

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/raspi-config" ]; then
		update-rc.d raspi-config defaults >/dev/null || exit $?
	fi
fi
# End automatically added section

